# .github/workflows/build.yml

name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        sudo apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
                          libreadline-dev libsqlite3-dev wget curl llvm \
                          libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev \
                          liblzma-dev python3-dev libjpeg-dev
        pip install --upgrade pip
        pip install buildozer

    - name: Install Buildozer dependencies
      run: |
        sudo apt install -y libssl-dev libsqlite3-dev libz-dev \
                          libjpeg8-dev libfreetype6-dev liblcms2-dev \
                          libwebp-dev tcl-dev tk-dev libmysqlclient-dev

    - name: Run Buildozer to build the APK
      run: |
        buildozer android debug
